### PR TITLE
Lps 71601

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
@shuyangzhou @Preston-Crary, this was probably meant to be merged to the 1.1.x branch, which is the one used in master: https://github.com/liferay/liferay-portal/blob/master/lib/development/dependencies.properties#L2

right?

**Comment by shuyangzhou** [comment]
@brunobasto yes, this is meant to go into portal master, thanks! Do you need me to resend the pull?

**Comment by brunobasto** [comment]
No, it's ok. I can pick the commits. Thanks!

**Comment by brunobasto** [comment]
Hey @shuyangzhou, commits have been merged to https://github.com/liferay/alloy-taglibs/tree/1.1.x

Do you have permissions to publish this to nexus? By running `ant jar` you can generate the jar we use in portal. Andrea has recently changed the way we add this dependencies in portal to rely on gradle cache. So, we need to publish it to nexus now.

**Comment by shuyangzhou** [comment]
Thanks @brunobasto ! I don't think I can publish it. @Ithildir , can you help us on this?

**Comment by CAustin582** [comment]
@brunobasto you should now have the necessary permissions to publish to the following namespace in liferay-public-releases and liferay-public-snapshots:
group: com.liferay.alloy-taglibs
artifactID: alloy-taglib / alloy-web

Just let me know if there are any issues. Also, I can give the same permissions to others on your team if they need them.

**Comment by shuyangzhou** [comment]
Hey @brunobasto , @CAustin582 is going to send you an email to give you permission and instructions on how to publish it on your side.
Can you apply it to portal once it is published? Thanks!

**Comment by shuyangzhou** [comment]
Thanks @CAustin582 !

**Comment by brunobasto** [comment]
PR sent here: https://github.com/shuyangzhou/liferay-portal/pull/4151

Thanks, guys!

**Pull request closed without merging**
